#!/bin/bash

#1.Find Accession number, $1 present the marker to known in this situation is AC
awk '$1=="AC"{print $2}' U31362.1.gb |tr -d ';'

#2.Find Product name, remove column 1 by set it empty, find the pattern is product then use substring to remove the text "product to print out protein name"
awk '/product/ {$1="";print substr($0,11)}' U31362.1.gb|tr -d "\""

#3.Translation, find the translation pattern then print out all the line begin from "translation to the next round by using the whilde loop, if the loop reach "XX" which mean the end of acid amin sequences the break the loop. Next step is print out column 2 and remove word translation 
awk '/translation/{while(i=1){print $0;getline; if ($1=="XX"){break} } }' U31362.1.gb|awk '{print $2}'|tr -d '/translation="'
